### PR TITLE
Try traget pull_request instead of pull_request_target

### PR DESCRIPTION
**Pull request by Bouni**
This is an attempt to fix the pytest issue surfaced in #151

### CODE REVIEW

**Comment by Bouni** [comment]
@gerw My guess was wrong, this prints `(HEAD detached at pull/152/merge) 1fcdeb4 Merge c97a155cc37e44e42515b7721cf4b8340826235d into 3d94a5903fe1e104531bd481e4277dfc11668f1a` for `git branch -v` 😕 

@kbabioch Do you have an idea why the test seem to run on the wrong files ?

**Comment by Bouni** [comment]
Ok I think `pull_request_target` is indeed the problem, the tests for the trigger `pull_request` succeed!

**Comment by Bouni** [comment]
I would like to merge the pytest CI workflow with `pull_request_target` replaced with `pull_request` and see if that works for #151 as well.

Any thoughts?

**Comment by gerw** [comment]
LGTM. Thank you!

**Review by gerw — APPROVED** [review]

**Pull request merged**
