### PR TITLE
Add pylint as GitHub action to increase code quality and consistency

### PR DESCRIPTION
**Pull request by kbabioch**
This adds a GitHub action that will lint all Python files with pylint. This will ensure that the code will be more consistent when multiple persons are working on it. Also it will warn us about potential issues.

In case we don't like specific rules, the linter can be disabled for specific files and code sections and also re-configured. The output is verbose and solutions to reported issues can typically be easily found by searching the Internet (TM).

### CODE REVIEW

**Comment by Bouni** [comment]
@kbabioch This PR dows contain much more than just the pylint GH action. Can you please fix this as things will get messy if I merg it like this (This is somehow mixed with commits from #37 )

**Comment by kbabioch** [comment]
Ah, my mistake, yes, will clean it up, sorry.

**Comment by Bouni** [comment]
No problem, stuff like this happens to me al now an then as well 😆

**Comment by kbabioch** [comment]
Okay, fixed the pull request, should be merge-able now :-).

**Comment by Bouni** [comment]
Perfect, thanks @kbabioch

**Pull request merged**
