### PR TITLE
New datatypes for timer programs

### PR DESCRIPTION
**Pull request by gerw**
I have added some datatypes to read (and change) the settings related to the timer programs of the heat pump.

Parameters 161-221 seem to have a similar meaning, but I do not know how they can be checked / set from the heat pump controller. Moreover, the reading of parameter 161 is `6` for me, which does not fit the scheme of the other settings..

I have not allowed to set the timers related to the mixing circuits (`MK`) and swimming pool (`Swb`), since these are not available at my heat pump (and so I cannot check these settings).

Finally, for the air ventilation `Luf` (Parameters 895-955) and for the "silent inverter" (Parameters 1092-1113), the storage format seems to be different, both time stamps (without seconds) are saved in one parameter slot. Does anybody have reasonable readings for these settings? Is the "silence" setting used for air source heat pumps to limit the noise, e.g., during nights?

One thing is open to discussion: I converted the raw value into strings, e.g., "9:00" or "10:00-14:00". I think that a string is the simplest option from the users perspective, e.g., for `parameters.set(507, "9:00")` or `parameters.set(896, "1:00-12:00")`. What do you think?

### CODE REVIEW

**Comment by Bouni** [comment]
@gerw 

Same for me for Parameter 161:

```
Number: 161   Name: ID_Einst_SuAll_akt2   Type: Unknown   Value: 6
```

I think there are a lot more that use this timer type, if I do a `luxtronik dump 192.168.178.11 | grep "ID_Einst_.*zeit"` I get 621 results.

- 162-167 ID_Einst_SuAllWo 
- 168-179 ID_Einst_SuAll25
- 180-221 ID_Einst_SuAllTg
- 223-228 ID_Einst_SuHkrW0
- 229-240 ID_Einst_SuHkr25
- 241-282 ID_Einst_SuHkrTG
- 284-289 ID_Einst_SuMk1W0
- 290-301 ID_Einst_SuMk125
- 302-343 ID_Einst_SuMk1TG
- 345-350 ID_Einst_SuMk2Wo
- 351-362 ID_Einst_SuMk225
- 363-404 ID_Einst_SuMk2Tg
- 406-415 ID_Einst_SuBwWO
- 416-435 ID_Einst_SuBw25
- 436-505 ID_Einst_SuBwTG
- 507-516 ID_Einst_SuZIPWo
- 517-536 ID_Einst_SuZIP25
- 537-606 ID_Einst_SuZIPTg
- 608-613 ID_Einst_SuSwbWo
- 614-625 ID_Einst_SuSwb25
- 626-667 ID_Einst_SuSwbTg
- 789-794 ID_Einst_SuMk3Wo
- 795-806 ID_Einst_SuMk325
- 807-848 ID_Einst_SuMk3Tg
- 896-898 ID_Einst_SuLufWo
- 899-904 ID_Einst_SuLuf25
- 905-925 ID_Einst_SuLufTg
- 926-928 ID_Einst_SuLufWo
- 929-934 ID_Einst_SuLufTg
- 935-955 ID_Einst_SuLufTg

They all follow a pattern, i guess those with Wo is "Woche", 25 is Monday through Friday  and Tg is "Tag".
The last few "SuLuf.." seem to bit in disorder for some reason.

My guess:

- All = Allgemein
- Hkr = Heizkreis
- Mk1 = Mischkreis 1
- Bw = Brunnenwasser
- ZIP = Zirkulationspumpe
- Swb = Schwimmbad
- MK3 = Mischkreis 3
- Luf = ??

**Comment by kbabioch** [comment]
> Is the "silence" setting used for air source heat pumps to limit the noise, e.g., during nights?

Yes, AFAIK this is the idea and I've read about it in some manual, but haven't used it myself.

> One thing is open to discussion: I converted the raw value into strings, e.g., "9:00" or "10:00-14:00". I think that a string is the simplest option from the users perspective, e.g., for `parameters.set(507, "9:00")` or `parameters.set(896, "1:00-12:00")`. What do you think?

For me that is fine. The alternative (dedicated datatype?) seems more complicated ...

**Review by kbabioch — APPROVED** [review]

**Comment by kbabioch** [comment]
Seems like this addresses (and will close) #33.

**Comment by gerw** [comment]
> > Is the "silence" setting used for air source heat pumps to limit the noise, e.g., during nights?
> 
> Yes, AFAIK this is the idea and I've read about it in some manual, but haven't used it myself.

IIRC, you have a air heat pump? Do you have this setting available? Could you test whether the conversion is correct?

**Comment by gerw** [comment]
> They all follow a pattern, i guess those with Wo is "Woche", 25 is Monday through Friday and Tg is "Tag". The last few "SuLuf.." seem to bit in disorder for some reason.

`25` means you have a setting for the week end (`2`) and a different setting for Monday-Friday (`5`).

> My guess:
> 
>     * All = Allgemein
> 
>     * Hkr = Heizkreis
> 
>     * Mk1 = Mischkreis 1
> 
>     * Bw = Brunnenwasser
> 
>     * ZIP = Zirkulationspumpe
> 
>     * Swb = Schwimmbad
> 
>     * MK3 = Mischkreis 3
> 
>     * Luf = ??

`Luf` is `Lüftung` (ventilation) I would guess. And there seem to be two sets of timer settings for the ventilation.

Finally, `Luf` and `Silence` use a compressed storage for the timer settings, therefore they only have half as many settings.

**Pull request merged**
