### PR TITLE
Fix test

### LINKED ISSUE #150: Datatypes test fails
After merging #142 the datatypes test fails:

https://github.com/Bouni/python-luxtronik/actions/runs/7784910695/job/21226348609#step:5:38

@gerw could you take a closer look why?

### PR DESCRIPTION
**Pull request by gerw**
Fixes #150

### CODE REVIEW

**Comment by gerw** [comment]
Am I being crazy? Why does `pytest` fails exactly at the line which I have changed? Does it test the previous version of the code?

**Review by kbabioch — APPROVED** [review]

**Comment by Bouni** [comment]
🤔 Can you try to rebase onto main? Maybe something went wrong there !?

**Comment by gerw** [comment]
I think there is nothing to rebase here. This PR is directly one commit below main, isn't it?

**Comment by gerw** [comment]
Now, the publishing of the code coverage seems to fail. I think we already had this issue at some time in the past?

**Comment by Bouni** [comment]
I'll look into it tomorrow

**Comment by Bouni** [comment]
Guess I found a solution:

https://github.com/MishaKav/pytest-coverage-comment/issues/68#issuecomment-1229144760

Will add the permissions tomorrow

**Comment by Bouni** [comment]
Ok, Chat GPT sucks as it proposed wrong inputs for the coverage action 🤦🏽‍♂️ 
I simply don't understand why it works if I do a PR but not for you ...

Maybe because I'm the owner of the repo and you just a contributer!?

I'll try to find another solution ...

**Comment by gerw** [comment]
No, I think that the problem is that your PRs come directly from this repo, but my PR come from a different repo. In principle, everybody could file a PR with (potentially malicious) code and this should not be executed with the permissions of this repo.

**Comment by gerw** [comment]
What happens if you change `repo-token` to `github-token`?

**Comment by Bouni** [comment]
I don't know, lets try.

**Comment by Bouni** [comment]
I just changed the actions settings in the hope that it fixes the problem, can you do `git commit --allow-empty -m "Trigger-CI"` to see if that works?

**Comment by gerw** [comment]
Now, the workflows seem to fail already at startup...

**Comment by Bouni** [comment]
Ok then I'll put the settings back to original and continue to search for a solution

**Comment by Bouni** [comment]
I guess I found the answer in this blog post

https://securitylab.github.com/research/github-actions-preventing-pwn-requests/

I'll try to create a two staged coverage ci workflow tomorrow

**Comment by Bouni** [comment]
@gerw Now everything runs but `MishaKav/pytest-coverage-comment@main` gives this error:

```
Warning: This action supports comments only on `pull_request`, `pull_request_target`, `push` and `workflow_dispatch`  events. `workflow_run` events are not supported.
```

So still no coverage report for forked repo PRs but at least the pytest CI workflow works.

I'll see if I can fix this somehow. Anyway, now we can continue with the real work on `python-luxtronik` 🥳

**Pull request merged**
