### PR TITLE
Datatype minute, change datatypes

### PR DESCRIPTION
**Pull request by BenPru**
### Changed - Make writeable and change datatype
- ID_Einst_LGST_akt --> Celsius
- ID_Einst_TAbsMin_akt --> Celsius
- ID_Einst_Minimale_Ruecklaufsolltemperatur --> Celsius
- ID_Einst_ZWEFreig_akt --> Celsius
- ID_Einst_HRHyst_akt --> Kelvin
- ID_Einst_TRErhmax_akt --> Kelvin
- ID_Einst_Popt_Nachlauf_akt --> Minutes
- ID_Einst_Freigabe_Zeit_ZWE --> Minutes

### Added
* New datatype minutes.

### CODE REVIEW

**Comment by kbabioch** [comment]
Do you happen to know what those parameters actually do. I can see that you add / set / update the data types, but there is no real explanation about the parameters itself.

I'm currently preparing a documentation for this, so maybe you could add a few word (either in German / English) about those parameters, so that I could consider this in my documentation. Otherwise I only see / know what the datatype is, but not what it actually means :-).

Affected parameters are:

- ID_Einst_LGST_akt
- ID_Einst_HRHyst_akt
- ID_Einst_TRErhmax_akt
- ID_Einst_ZWEFreig_akt
- ID_Einst_TAbsMin_akt
- ID_Einst_Popt_Nachlauf_akt
- ID_Einst_Minimale_Ruecklaufsolltemperatur
- ID_Einst_Freigabe_Zeit_ZWE

For instance, I've tried to document the meaning of parameter 107 extensively with my commit messages and the pull request (#42).

**Comment by kbabioch** [comment]
Do you happen to know what those parameters actually do. I can see that you add / set / update the data types, but there is no real explanation about the parameters itself.

I'm currently preparing a documentation for this, so maybe you could add a few word (either in German / English) about those parameters, so that I could consider this in my documentation. Otherwise I only see / know what the datatype is, but not what it actually means :-).

Affected parameters are:

- ID_Einst_LGST_akt
- ID_Einst_HRHyst_akt
- ID_Einst_TRErhmax_akt
- ID_Einst_ZWEFreig_akt
- ID_Einst_TAbsMin_akt
- ID_Einst_Popt_Nachlauf_akt
- ID_Einst_Minimale_Ruecklaufsolltemperatur
- ID_Einst_Freigabe_Zeit_ZWE

I assume that anything ending with `_akt` means something `aktiv seit`, i.e. `active since`. Is that correct?

What does `ID_Einst_Freigabe_Zeit_ZWE` mean then? What is `LGST`, `HRHyst`, `TRErhmax`, `ZWEFreig`, `TAbsMin`, `Popt_Nachlauf`?

For instance, I've tried to document the meaning of parameter 107 extensively with my commit messages and the pull request (#42).

**Comment by BenPru** [comment]
```
paramter_docs = {
    47: {
        "entity_key_legacy": "ID_Einst_LGST_akt",
        "entity_key": "domestic_water_thermal_desinfection_target",
        "name": _("Domestic water thermal desinfection target temperature"),
        "description": _("TDI setpoint temperature\nSetting for the setpoint temperature for the thermal disinfection in the domestic hot water preparation."),
        "min": 50.0,
        "max": 70.0,
        "step": 1.0,
        "unit_of_measurement": "C°"
    },
    88: {
        "entity_key_legacy": "ID_Einst_HRHyst_akt",
        "entity_key": "heating_hysteresis",
        "name": _("Hysteresis heating regulator"),
        "description": _("setting for the control hysteresis of the heating regulator.\nSet a greater hysteresis for very reactive heating systems, and a lower hysteresis for less reactive heating systems."),
        "min": 0.5,
        "max": 6.0,
        "step": 0.1,
        "unit_of_measurement": "K"
    },
    89: {
        "entity_key_legacy": "ID_Einst_TRErhmax_akt",
        "entity_key": "heating_max_flow_out_increase_temperature",
        "name": _("Heating maximum flow out increase temperature"),
        "description": _("Setting for the maximum permissible overshoots of the return temperature.\nIf the return temperature is overshot, internal minimum running times are ignored and all heat generators switched off.\nAlways set value higher than the value of the hysteresis HR."),
        "min": 1.0,
        "max": 10.0,
        "step": 0.1,
        "unit_of_measurement": "K"
    },
    90: {
        "entity_key_legacy": "ID_Einst_ZWEFreig_akt",
        "entity_key": "release_second_heat_generator",
        "name": _("Release second heat generator"),
        "description": _("Setting for the external temperature from which the second heat generator can be released if required. Above the set external temperature, the second heat generators remain locked.\nException:\nIn the event of a fault and the setting fault with a ZWE, the second heat generators are released independently of the set external temperature."),
        "min": -20.0,
        "max": 20.0,
        "step": 0.1,
        "unit_of_measurement": "C°"
    },
    111: {
        "entity_key_legacy": "ID_Einst_TAbsMin_akt",
        "entity_key": "heating_night_lowering_to_temperature",
        "name": _("Heating night lowering to temperature"),
        "description": _("Setting for the external temperature up to which a night lowering is carried out.\nIf the actual external temperature falls below the set value, the lowering temperature is ignored."),
        "min": -20.0,
        "max": 10.0,
        "step": 0.5,
        "unit_of_measurement": "C°"
    },
    864: {
        "entity_key_legacy": "ID_Einst_Popt_Nachlauf_akt",
        "entity_key": "pump_optimization_time",
        "name": _("Pump optimization time"),
        "description": _("If the pump optimisation is switched on (Pump opt. = Yes), the time be defined, according to which the heating circulation pumps are switched off.\nIf the heat pump is off during this time because there is no need for heating, the pump will loop - 30 minutes off, 5 minutes on, until there is a further heating requirement."),
        "min": 5,
        "max": 180,
        "step": 5,
        "unit_of_measurement": "min"
    },
    979: {
        "entity_key_legacy": "ID_Einst_Minimale_Ruecklaufsolltemperatur",
        "entity_key": "heating_min_flow_out_temperature",
        "name": _("Heating min flow out temperature"),
        "description": _("Minimum return set-point temperature.\nWill not be exceeded in operation."),
        "min": 5.0,
        "max": 30.0,
        "step": 0.5,
        "unit_of_measurement": "C°"
    },
    992: {
        "entity_key_legacy": "ID_Einst_Freigabe_Zeit_ZWE",
        "entity_key": "release_time_second_heat_generator",
        "name": _("Release time second heat generator"),
        "description": _("Time until the second heat generator is switched on"),
        "min": 20,
        "max": 120,
        "step": 5,
        "unit_of_measurement": "min"
    }
}

```

**Comment by kbabioch** [comment]
Cool information! Where do you have min,ax, step values from?

**Comment by BenPru** [comment]
> Cool information! Where do you have min,ax, step values from?

Original documentation:
https://files.ait-group.net/FILES/Alpha-InnoTec/manuals/01%20heat%20pumps/05%20controller/LUX/83055300gUK_Lux_20_Teil_2.pdf
https://files.ait-group.net/FILES/Alpha-InnoTec/Betriebsanleitungen/01%20Waermepumpen/05%20Regler/LUX/83055300gDE_Lux_20_Teil_2.pdf

**Pull request merged**
