### PR TITLE
Fix several typos throughout code base

### PR DESCRIPTION
**Pull request by kbabioch**
This addresses several typos in the strings throughout the code base (code list mappings, log messages, docstrings, etc.).

### CODE REVIEW

**Comment by Bouni** [comment]
Lgtm

**Comment by kbabioch** [comment]
> Lgtm

Then feel free to go ahead with the merge :-).

I have some more changes regarding the README.md in the pipeline, but those are a general improvement of the documentation and not related to this one here. From my point of view this MR is as ready as it will get :-).

**Comment by Bouni** [comment]
I'm not near a computer and GitHub mobile refuse to rebase and merge

**Comment by Bouni** [comment]
I'm not near a computer and GitHub mobile refuse to rebase and merge

**Comment by kbabioch** [comment]
Ah, now I understand the problem. I've rebased this change set on top of your current `main`, so no further rebasing needed. Should be possible to merge this by simply pressing the button. Of course, only do so when you're ready / available.

**Pull request merged**
